server:
  port: 8201
spring:
  profiles:
    active: dev
  application:
    name: service-hosp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    root: debug